# Generated by Django 4.1.1 on 2022-10-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="frist_name",
            new_name="first_name",
        ),
    ]
